#%RAML 0.8
#RAML for Atomic Measurement.
#
title: Atomic Measurement
version: 0.1
documentation:

  - title: OCF Copyright
    content: Copyright (c) 2016, 2017 Open Connectivity Foundation, Inc. All rights reserved.
  - title: OCF License
    content: !include LICENSE.md
  - title: OCF Disclaimer
    content: !include DISCLAIMER.md
  - title: Atomic Measurement
    content: |
      Atomic Measurement is a specialization of the OCF Collection, which is an
      extension of OIC Resource.

  - title: Atomic Measurement Restrictions on included resources
    content: |
      Atomic Measurement restricts properties to be exposed only through the
      oic.if.b interface of the Atomic Measurement, thus ensuring that all
      of the items are accessed "atomically" as a batch.

  - title: Resource Design
    content: |
      The Atomic Measurement resource is specified as three Base URIs, one
      for each interface which is supported by the collection.

      These three URIs are defined as the same URI path, only distinguished
      by the different query parameter traits.

schemas:
  - baseline: !include schemas/oic.collection-schema.json
  - batch-retrieve: !include schemas/oic.collection.batch-retrieve-schema.json
  - links: !include schemas/oic.collection.linkslist-schema.json

traits:
  - interface-all:
      queryParameters:
        if:
          enum: ["oic.if.b", "oic.if.ll", "oic.if.baseline"]

  - interface-baseline:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

  - interface-b:
      queryParameters:
        if:
          enum: ["oic.if.b"]

  - interface-ll:
      queryParameters:
        if:
          enum: ["oic.if.ll"]


/AtomicMeasurementURI?if=oic.if.baseline:
  description: |
    The oic.if.baseline interface exposes a representation of the links and
    the common properties of the Atomic Measurement resource.

  displayName: Baseline Interface
  is: [ interface-baseline ]

  get:
    description: |
      Retrieve on Baseline Interface

    responses:
      200:
        body:
          application/json:
            schema: baseline
            example: |
              {
                "rt": ["oic.wk.col.atomic"],
                "if": ["oic.if.b", "oic.if.ll", "oic.if.baseline"]
                "rts": [ "oic.r.temperature", "oic.r.body.location.temperature", "oic.r.time.observed" ],
                "links": [
                  {
                    "href": "temperature",
                    "rt":   ["oic.r.temperature"],
                    "if":   ["oic.if.s", "oic.if.baseline"],
                  },
                  {
                    "href": "bodylocation",
                    "rt":   ["oic.r.body.location.temperature"],
                    "if":   ["oic.if.s", "oic.if.baseline"],
                  },
                  {
                    "href": "timestamp",
                    "rt":   ["oic.r.time.observed"],
                    "if":   ["oic.if.s", "oic.if.baseline"],
                  }
                ]
              }


/AtomicMeasurementURI?if=oic.if.b:
    description: |
      The oic.if.b interface returns data items retrieved from resources pointed to by the links.

    displayName: Batch Representation
    is: [ interface-b ]

    get:
      description: |
        Retrieve the data elements of the Atomic Measurement using the OCF Batch Interface

      responses:
        200:
          description: |
             Normal response, no errors, all properties are returned correctly
          body:
            application/json:
              schema: batch-retrieve
              example: |
                [
                  {
                    "href": "temperature",
                    "rep":
                      {
                        "temperature": 38,
                        "units": "C",
                        "range": [25, 45]
                      }
                  },
                  {
                    "href": "bodylocation",
                    "rep":
                      {
                        "bloc": "ear"
                      }
                  },
                  {
                    "href": "timestamp",
                    "rep":
                      {
                        "observedtime": "2007-04-05T14:30+09:00"
                      }
                  }
                ]


/AtomicMeasurementURI?if=oic.if.ll:
    description: |
      The oic.if.ll interface exposes a representation of the links

    displayName: Link List Representation
    is: [ interface-ll ]

    get:
      description: |
        Retrieve on Link List Interface

      responses:
        200:
          body:
            application/json:
              schema: links
              example: |
                [
                  {
                    "href": "temperature",
                    "rt":   ["oic.r.temperature"],
                    "if":   ["oic.if.s", "oic.if.baseline"],
                  },
                  {
                    "href": "bodylocation",
                    "rt":   ["oic.r.body.location.temperature"],
                    "if":   ["oic.if.s", "oic.if.baseline"],
                  },
                  {
                    "href": "timestamp",
                    "rt":   ["oic.r.time.observed"],
                    "if":   ["oic.if.s", "oic.if.baseline"],
                  }
                ]
