#%RAML 0.8
title: software update
version: v1-20180413
documentation:

  - title: OCF Copyright
    content: Copyright (c) 2018 Open Connectivity Foundation, Inc. All rights reserved.
  - title: OCF License
    content: !include LICENSE.md
  - title: OCF Disclaimer
    content: !include DISCLAIMER.md

schemas:
  - software: !include schemas/oic.r.softwareupdate-schema.json
  - software-update: !include schemas/oic.r.softwareupdate-update-schema.json

traits:
  - interface-all:
      queryParameters:
        if:
          enum: ["oic.if.rw","oic.if.baseline"]
  - interface-rw:
      queryParameters:
        if:
          enum: ["oic.if.rw"]

/firmwareupdateResURI:
  displayName: software update
  description: |
    software update.
  get:
    is: [ interface-all ]
    description: Retrieve the software update information
    responses:
      200:
        body:
          application/json:
            schema: software
            example: |
               {
                 "rt":   ["oic.r.softwareupdate"],
                 "nv":  "my new version",
                 "packageurl":   "",
                 "action" : "idle",
                 "state" : "idle",
                 "result" : 0,
                 "updatetime" : "2017-01-09T14:30:00Z",
                 "lastupdate" : "2017-01-09T14:30:00Z",
                 "signage" : "vendor"
               }
  post:
    is: [ interface-rw ]
    description: |
      set scheduled update information, e.g. ask if a new version is available on the remote endpoint
      set data of origin of software package.
      note that the SVR resource /oic/sec/pstat tag tm can be used to start the software check or full upgrade.
    body:
      application/json:
        schema: software-update
        example: |
           {
             "packageurl" : "https://myvendorlocation/package.dat",
             "action":   "isac",
             "updatetime":   "2019-01-09T12:00:00Z"
           }
    responses:
      200:
        body:
          application/json:
            schema: software
            example: |
               {
                 "rt":   ["oic.r.softwareupdate"],
                 "nv":  "my new version",
                 "packageurl":   "https://myvendorlocation/package.dat",
                 "action" : "isac",
                 "state" : "idle",
                 "result" : 0,
                 "updatetime" : "2019-01-09T12:00:00Z",
                 "lastupdate" : "2017-01-09T14:30:00Z",
                 "signage" : "vendor"
               }
